DOMAIN = "scene_presets"
NAME = "Scene Presets"

PANEL_URL = "/scene_presets_panel.js"

SERVICE_APPLY_PRESET = "apply_preset"
SERVICE_START_DYNAMIC_SCENE = "start_dynamic_scene"
SERVICE_STOP_DYNAMIC_SCENE = "stop_dynamic_scene"
SERVICE_STOP_ALL_DYNAMIC_SCENES = "stop_all_dynamic_scenes"
SERVICE_STOP_DYNAMIC_SCENES_FOR_TARGETS = "stop_dynamic_scenes_for_targets"
SERVICE_GET_DYNAMIC_SCENES = "get_dynamic_scenes"
SERVICE_GET_FAVORITES = "get_favorites"
SERVICE_IS_FAVORITE = "is_favorite"
SERVICE_SET_FAVORITES = "set_favorites"
SERVICE_ADD_FAVORITE = "add_favorite"
SERVICE_REMOVE_FAVORITE = "remove_favorite"
SERVICE_TOGGLE_FAVORITE = "toggle_favorite"

ATTR_SCENE_PRESET_ID = "preset_id"
ATTR_TARGETS = "targets"
ATTR_BRIGHTNESS = "brightness"
ATTR_TRANSITION = "transition"
ATTR_SHUFFLE = "shuffle"
ATTR_SMART_SHUFFLE = "smart_shuffle"
ATTR_INTERVAL = "interval"
ATTR_STOP_ON_MANUAL_CHANGE = "stop_on_manual_change"
ATTR_USER_ID = "user_id"
ATTR_FAVORITES = "favorites"

ATTR_DYNAMIC_SCENE_ID = "id"

DATA_FAVORITES_STORE = "favorites_store"
